loader:
  ros__parameters:
    yaml_temel_adi: ajanlar_avm
    simulator: Gazebo Classic
    harita: warehouse
    insanlari_yayinla: true
    
    # AVM (Alisveris Merkezi) Senaryosu - 150 mÂ² Alan (15m x 10m)
    # Toplam: 12 ajan
    # Yetiskin (26-60): 6 kisi (%50) - Notr - Orta (0.50-0.60 m/s)
    # Genc (13-25): 3 kisi (%25) - Merakli/Notr - Orta-Hizli (0.65-0.75 m/s)
    # Cocuk (0-12): 2 kisi (%16.7) - Merakli - Hizli (0.80-0.90 m/s)
    # Yasli (60+): 1 kisi (%8.3) - Cekingen - Yavas (0.40 m/s)
    
    # Sosyal Tutum Dagilimi:
    # - Notr: 6 kisi (%50)
    # - Merakli: 4 kisi (%33.3)
    # - Cekingen: 2 kisi (%16.7)
    
    genel_hedefler:
      1:
        x: 0.920
        y: 5.779
      2:
        x: 0.850
        y: -7.784
      3:
        x: -3.678
        y: 7.331
      4:
        x: -3.613
        y: -7.366
      5:
        x: -2.647
        y: -4.476
      6:
        x: 1.605
        y: -4.393
      7:
        x: 1.398
        y: 0.340
      8:
        x: -2.260
        y: 0.295
      9:
        x: 2.500
        y: 3.000
      10:
        x: -1.000
        y: -2.500
      11:
        x: 3.200
        y: -1.500
      12:
        x: -3.800
        y: -2.000
    
    ajanlar:
      - ajan1
      - ajan2
      - ajan3
      - ajan4
      - ajan5
      - ajan6
      - ajan7
      - ajan8
      - ajan9
      - ajan10
      - ajan11
      - ajan12
    
 
    ajan1:
      id: 1
      grup_id: -1
      gorunum: 2  
      maks_hiz: 0.55
      yaricap: 0.40
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: 0.800
        y: 5.500
        z: 1.250
        h: -1.500
      davranis:
        tip: Notr  
        yapilandirma: 1
        hedef_kuvvet_carpan: 2.5
        engel_kuvvet_carpan: 10.0
        sosyal_kuvvet_carpan: 5.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 1
        - 7
    
    ajan2:
      id: 2
      grup_id: -1
      gorunum: 2
      maks_hiz: 0.52
      yaricap: 0.40
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: -3.200
        y: 6.800
        z: 1.250
        h: 0.000
      davranis:
        tip: Notr  
        yapilandirma: 1
        hedef_kuvvet_carpan: 2.5
        engel_kuvvet_carpan: 10.0
        sosyal_kuvvet_carpan: 5.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 3
        - 8
    
    ajan3:
      id: 3
      grup_id: -1
      gorunum: 2
      maks_hiz: 0.58
      yaricap: 0.40
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: 0.500
        y: -7.200
        z: 1.250
        h: 1.500
      davranis:
        tip: Notr 
        yapilandirma: 1
        hedef_kuvvet_carpan: 2.5
        engel_kuvvet_carpan: 10.0
        sosyal_kuvvet_carpan: 5.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 2
        - 6
    
    ajan4:
      id: 4
      grup_id: -1
      gorunum: 2
      maks_hiz: 0.50
      yaricap: 0.40
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: -3.300
        y: -7.000
        z: 1.250
        h: 1.000
      davranis:
        tip: Notr  
        yapilandirma: 1
        hedef_kuvvet_carpan: 2.5
        engel_kuvvet_carpan: 10.0
        sosyal_kuvvet_carpan: 5.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 4
        - 9
    
    ajan5:
      id: 5
      grup_id: -1
      gorunum: 2
      maks_hiz: 0.60
      yaricap: 0.40
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: 1.500
        y: 0.300
        z: 1.250
        h: 0.000
      davranis:
        tip: Notr  
        yapilandirma: 1
        hedef_kuvvet_carpan: 2.5
        engel_kuvvet_carpan: 10.0
        sosyal_kuvvet_carpan: 5.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 7
        - 11
    
    ajan6:
      id: 6
      grup_id: -1
      gorunum: 2
      maks_hiz: 0.54
      yaricap: 0.40
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: -2.500
        y: -4.200
        z: 1.250
        h: 0.500
      davranis:
        tip: Cekingen  
        mesafe: 2.000
        yapilandirma: 1
        hedef_kuvvet_carpan: 2.5
        engel_kuvvet_carpan: 10.0
        sosyal_kuvvet_carpan: 5.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 5
        - 10
    
   
    ajan7:
      id: 7
      grup_id: -1
      gorunum: 1  
      maks_hiz: 0.70
      yaricap: 0.35
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: 2.200
        y: 2.800
        z: 1.250
        h: -2.000
      davranis:
        tip: Merakli 
        mesafe: 1.800
        sure: 18.00
        bir_kere: false
        yapilandirma: 2
        hedef_kuvvet_carpan: 2.8
        engel_kuvvet_carpan: 9.0
        sosyal_kuvvet_carpan: 4.5
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 9
        - 3
    
    ajan8:
      id: 8
      grup_id: -1
      gorunum: 1
      maks_hiz: 0.65
      yaricap: 0.35
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: -0.800
        y: -2.200
        z: 1.250
        h: 0.800
      davranis:
        tip: Notr
        yapilandirma: 2
        hedef_kuvvet_carpan: 2.8
        engel_kuvvet_carpan: 9.0
        sosyal_kuvvet_carpan: 4.5
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 10
        - 1
    
    ajan9:
      id: 9
      grup_id: -1
      gorunum: 1
      maks_hiz: 0.75
      yaricap: 0.35
      hedef_yaricap: 0.30
      dongusel_hedefler: true
      baslangic_konum:
        x: 1.800
        y: -2.000
        z: 1.250
        h: -0.300
      davranis:
        tip: Merakli 
        mesafe: 1.800
        sure: 18.00
        bir_kere: false
        yapilandirma: 2
        hedef_kuvvet_carpan: 2.8
        engel_kuvvet_carpan: 9.0
        sosyal_kuvvet_carpan: 4.5
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 7
        - 12
    
    
    ajan10:
      id: 10
      grup_id: -1
      gorunum: 0  
      maks_hiz: 0.85
      yaricap: 0.30
      hedef_yaricap: 0.25
      dongusel_hedefler: true
      baslangic_konum:
        x: 0.600
        y: 5.800
        z: 1.250
        h: -1.500
      davranis:
        tip: Merakli 
        mesafe: 1.500
        sure: 15.00
        bir_kere: false
        yapilandirma: 2
        hedef_kuvvet_carpan: 3.0
        engel_kuvvet_carpan: 8.0
        sosyal_kuvvet_carpan: 3.5
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 1
        - 6
    
    ajan11:
      id: 11
      grup_id: -1
      gorunum: 0
      maks_hiz: 0.80
      yaricap: 0.30
      hedef_yaricap: 0.25
      dongusel_hedefler: true
      baslangic_konum:
        x: 1.400
        y: -4.000
        z: 1.250
        h: -0.500
      davranis:
        tip: Notr 
        yapilandirma: 2
        hedef_kuvvet_carpan: 3.0
        engel_kuvvet_carpan: 8.0
        sosyal_kuvvet_carpan: 3.5
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 6
        - 4
    

    ajan12:
      id: 12
      grup_id: -1
      gorunum: 3 
      maks_hiz: 0.40
      yaricap: 0.45
      hedef_yaricap: 0.40
      dongusel_hedefler: true
      baslangic_konum:
        x: -3.200
        y: 2.500
        z: 1.250
        h: 2.500
      davranis:
        tip: Cekingen 
        mesafe: 2.500
        yapilandirma: 0
        hedef_kuvvet_carpan: 1.8
        engel_kuvvet_carpan: 12.0
        sosyal_kuvvet_carpan: 7.0
        diger_kuvvet_carpan: 20.0
      hedefler:
        - 8
        - 11
